name: jtst
version: 0.0.2
summary: jtst
description: |
  jtst

confinement: strict
base: core18

parts:
  jtst:
    plugin: nil
    source: .
    override-build: |
      sed -i "s/commit_id = NULL/commit_id = \"$(git rev-list HEAD | head -n 1 | tr -d [:space:])\"/" version.h
      make
      mv sudoku ../install/jtst
    stage:
      - jtst

apps:
  jtst:
    command: jtst
